### ISSUE TITLE
Gitea API ref causing build failure

### ISSUE THREAD

**Issue by Kelmory** [drone/go-scm#105]
Gitea has changed their API for getting commit refs in their recent version `1.15.0+dev-183-gec69f3472`. 
Now the reference of commit head should be fetched using 
![image](https://user-images.githubusercontent.com/26181355/115964157-a9880900-a555-11eb-98c8-7ad16f340904.png)

The `/commit/` has somehow been removed from the URL. Meanwhile, the drone container lists the commits with https://github.com/drone/go-scm/blob/5aefd358cc7eac029eed7594d51ade36fe0403b9/scm/driver/gitea/git.go#L32

Could you please confirm if this is a bug or it's possibly because of other issues?

**Comment by bradrydzewski** [comment]
If Gitea introduced a breaking change in a development build of a minor release, should this be considered a Gitea regression and should an issue be opened in the Gitea repository?   One would expect breaking changes to be reserved for major release, such as a 2.0.0 release.

**Comment by Kelmory** [comment]
Thank you for explaining, brad. I checked the previous versions of Gitea and the API had already changed even in 1.9.0 (released in July 2019). As shown in its API document, there is only one API that contains `git/commits/` and the last field is `sha` rather than `ref`:
![image](https://user-images.githubusercontent.com/26181355/115970416-ced83f80-a574-11eb-89ab-8d043e7148f9.png)
![image](https://user-images.githubusercontent.com/26181355/115970487-32626d00-a575-11eb-9c21-5ac755c17abc.png)

Then I checked the file blame of `scm/driver/gitea/git.go` and I found the route url hasn't been changed for 2 years (before April 2019).
![image](https://user-images.githubusercontent.com/26181355/115970213-92581400-a573-11eb-91ba-dc3dd428fdd9.png)

So I think this is where the problem is. Cheers.

**Comment by tboerger** [comment]
I'm not sure if this report is really right, as https://try.gitea.io/api/swagger#/repository/repoGetSingleCommit still provides the required endpoint which doesn't show any breaking change.

**Comment by tboerger** [comment]
If it's named sha or ref should not matter as long as the result is correct.

**Comment by Kelmory** [comment]
Thanks for checking that API, Thomas. I have just found that the problem is not caused by the client-side. It's possibly because of a database error in the Gitea distribution of mine. Thank you.
