### ISSUE TITLE
Any plans to support manage wehook

### ISSUE THREAD

**Issue by LinuxSuRen** [drone/go-scm#134]
It would be great to support adding, deleting, updating a webhook of a git provider.

I'd be happy to help with this.

**Comment by bradrydzewski** [comment]
👋 hey there, this is currently supported by this package:
https://pkg.go.dev/github.com/drone/go-scm@v1.16.2/scm#example-Hook-Create

note that when creating hooks you should use `NativeEvents` since `Events` is being deprecated:

```Go
	input := &scm.HookInput{
		Name:       "CI",
		Target:     "https://ci.example.com",
		Secret:     "topsecret",
		SkipVerify: false,
		NativeEvents: []string{"issue_comment", "issues"},
	}

	_, _, err = client.Repositories.CreateHook(ctx, "octocat/Hello-World", input)
`

**Comment by LinuxSuRen** [comment]
hi @bradrydzewski , thanks for your quick response. Sorry I didn't go through the whole repo. I just try to find it from [WebService interface](https://github.com/drone/go-scm/blob/fdfe23995f39c97b2001dd78746deb4772401fb1/scm/webhook.go#L124)

Great!
