### ISSUE TITLE
The deprecation of Bitbucket API endpoint /2.0/teams breaks user registration

### ISSUE THREAD

**Issue by RandiHBK** [drone/go-scm#136]
Hello,

I failed to register a new user with Bitbucket account with the error message below:

This endpoint has been removed. See our documentation for more information. https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/

It looks like Bitbucket has deprecated the API endpoint /2.0/teams ​which Drone used to check whether a user is a member of a team. Is there plan to upgrade from /2.0/teams to /2.0/workspaces?

Thank you

**Comment by jbovet** [comment]
Update:
@eoinmcafee00 has sent PR https://github.com/drone/go-scm/pull/137 

LGTM.

**Comment by eoinmcafee00** [comment]
Issue has been resolved with this release https://github.com/harness/drone/releases/tag/v2.7.3
