### ISSUE TITLE
Bitbucket Server (Stash) Write Access

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-scm#15]
Find method to determine if user has write access

---

First I want to document how we handled this in 0.8

In 0.8 we use the following webhook to check and see if a user has access to the repository webhooks. If yes, the user is granted admin and write access:

```Go
var pathHook = "/rest/api/1.0/projects/%s/repos/%s/settings/hooks/%s"

func (c *Client) FindRepoPerms(owner string, repo string) (*model.Perm, error) {
	perms := new(model.Perm)
	// If you don't have access return none right away
	_, err := c.FindRepo(owner, repo)
	if err != nil {
		return perms, err
	}
	// Must have admin to be able to list hooks. If have access the enable perms
	resp, err := c.client.Get(fmt.Sprintf(pathHook, c.base, owner, repo, hookName))
	if resp != nil {
		defer resp.Body.Close()
	}
	if err == nil {
		perms.Push = true
		perms.Admin = true
	}
	perms.Pull = true
	return perms, nil
}
```

The source code can be found here:
https://github.com/drone/drone/blob/v0.8.8/remote/bitbucketserver/internal/client.go#L123:L140

The 1.0 version of Drone uses this exact same logic which can be found here:
https://github.com/drone/go-scm/blob/master/scm/driver/stash/repo.go#L118:L150

__ASSESSMENT__

There is a regression in the Drone UI that disables the cancel button for Drone system administrators if the admin does not have write/admin access to the repository. This only impacts the user interface and does not impact the ability for a system administrator to cancel a build via the API or the CLI.

Perhaps this UI regression is the difference you are noticing between 0.8 and 1.0?  Because there has been no change in underlying permissions enforced by the Drone server to cancel a build, nor have there been any changes to how we determine write/admin access?

**Comment by bradrydzewski** [comment]
It appears we may be able to use the combination of all of the following endpoints to determine if a user has write access to the repository. We need to check at the repository level, the project level, and at the system level:

* `/rest/api/1.0/projects/PRJ/repos/my-repo/permissions/users`
* `/rest/api/1.0/projects/PRJ/permissions/users`
* `/rest/api/1.0/admin/permissions/users`

**Comment by bradrydzewski** [comment]
> I tested the workaround and it seems to be working. Both URLs below return 200 status code but one has non-empty values field which means that person has write permission.
> 
> For a user who does not have write permission:
> ```
> curl https://bitbucket.example.com/rest/api/1.0/users \
>   ?filter=kowen.lu&permission=REPO_WRITE \
>   &permission.projectKey=RKSOPS \
>   &permission.repositorySlug=gitops-wifi
> ```
> ```
> {"size":0,"limit":25,"isLastPage":true,"values":[],"start":0}
> ```
> 
> 
> For a user who does have write permission:
> 
> ```
> curl https://bitbucket.example.com/rest/api/1.0/users \
>   ?filter=shahar.zeraviv&permission=REPO_WRITE \
>   &permission.projectKey=RKSOPS \
>   &permission.repositorySlug=gitops-wifi
> ```
> ```
> {"size":1,"limit":25,"isLastPage":true,"values":[{"name":"shahar.zeraviv","emailAddress":"shahar.zeraviv@ruckuswireless.com","id":1801,"displayName":"Shahar Zer-Aviv","active":true,"slug":"shahar.zeraviv","type":"NORMAL","links":{"self":[{"href":"https://bitbucket.example.com/users/shahar.zeraviv"}]}}],"start":0}
> ```

**Comment by bradrydzewski** [comment]
I also wanted to document how we handled this in 0.8

In 0.8 we use the following webhook to check and see if a user has access to the repository webhooks. If yes, the user is granted admin and write access:

```
var pathHook = "/rest/api/1.0/projects/%s/repos/%s/settings/hooks/%s"

func (c *Client) FindRepoPerms(owner string, repo string) (*model.Perm, error) {
	perms := new(model.Perm)
	// If you don't have access return none right away
	_, err := c.FindRepo(owner, repo)
	if err != nil {
		return perms, err
	}
	// Must have admin to be able to list hooks. If have access the enable perms
	resp, err := c.client.Get(fmt.Sprintf(pathHook, c.base, owner, repo, hookName))
	if resp != nil {
		defer resp.Body.Close()
	}
	if err == nil {
		perms.Push = true
		perms.Admin = true
	}
	perms.Pull = true
	return perms, nil
}
```

The source code can be found here:
https://github.com/drone/drone/blob/v0.8.8/remote/bitbucketserver/internal/client.go#L123:L140

The 1.0 version of Drone uses this exact same logic which can be found here:
https://github.com/drone/go-scm/blob/master/scm/driver/stash/repo.go#L118:L150

__NOTE__

There is a regression in the Drone UI that disables the cancel button for Drone system administrators if the admin does not have write/admin access to the repository. This only impacts the user interface and does not impact the ability for a system administrator to cancel a build via the API or the CLI.

Perhaps this is the change you are noticing between 0.8 and 1.0?  Because there has been no change in underlying permissions enforced by the Drone server to cancel a build, nor have there been any changes to how we determine write/admin access?

**Comment by bradrydzewski** [comment]
after some additional testing it looks like this method might work:

```
/rest/api/1.0/repos?permission=REPO_WRITE&name=my-repo&project=PRJ
/rest/api/1.0/repos?permission=REPO_ADMIN&name=my-repo&project=PRJ
```

**Comment by rvora** [comment]
The API documentation says it returns recently accessed repos. So it might not return the repo even if user has permission. Not sure but lets go with this API if it works for recently accessed repos.

Also, my testing shows that it returns sub-string matches e.g. if I have repos called my-repo and my-repo-123 then the call above will return both repos in the response.

I had this tested by non-admin user as well.

**Comment by bradrydzewski** [comment]
@rvora I am looking at the API docs and it does not mentioned the repository list being restricted to recently accessed repositories [1].  Note that this is the same endpoint we use to sync your repository list in Drone, so I think we should be ok.

In terms of sub-string matches, we have this handled. We iterate through the list and ensure an exact match of the repository name. You can see the patch at https://github.com/drone/go-scm/commit/47eed25fe462ac1ff69d10d9069f055d9b7b8457

I will publish rc.6 (the final release candidate) early next week which will include these changes. I need to do some testing before I can snapshot, but we are pretty close.

[1] https://docs.atlassian.com/bitbucket-server/rest/5.1.0/bitbucket-rest.html#idm45588158411872

**Comment by rvora** [comment]
Ok sounds good. Here's the doc I was reading (see bolded).

/REST/API/1.0/PROFILE/RECENT/REPOS?PERMISSION
This is a paged API. 

**Retrieve a page of recently accessed** repositories for the currently authenticated user.

Repositories are ordered from most recently to least recently accessed.

Only authenticated users may call this resource.
