### ISSUE TITLE
Rebuild Drone 1.0.0 RC6(?)

### ISSUE THREAD

**Issue by lflare** [drone/go-scm#16]
It seems that the patch for Gitea referenced over at https://github.com/drone/go-scm/issues/7 has not been built into a Docker image. How would I go about including this patch for the drone container I am currently running? @bradrydzewski, I noticed you also locked the original thread.

**Comment by tboerger** [comment]
The next rc will be built soon, brad got some tasks to finish before the next rc, and he will finally push the entire source to get the final version rolling soon.

**Comment by LFlare** [comment]
That's great to hear, do you happen to know a rough timeline?

**Comment by tboerger** [comment]
It's a matter of days.

**Comment by LFlare** [comment]
Awesome, I hope it'll be released within the week or so :)
