### ISSUE TITLE
gitee: When the name and path are inconsistent, got 404 error

### ISSUE THREAD

**Issue by KeJunMao** [drone/go-scm#217]
like this:

the repo name is [Storyline 360 User Guide](https://gitee.com/Ke_Jun/Storyline-360-User-Guide)

but the repo paht is `Storyline-360-User-Guide`

<img width="486" alt="ch07_2022-08-18 00 48 21" src="https://user-images.githubusercontent.com/18414281/185196960-ecba2dff-2105-4e2d-931d-3cd6477618f8.png">

in drone repo list: 
<img width="348" alt="ch07_2022-08-18 00 51 30" src="https://user-images.githubusercontent.com/18414281/185197576-d0542581-5f4e-4d84-b266-6025e49f37cb.png">

in drone repo detail:
<img width="713" alt="ch07_2022-08-18 00 51 38" src="https://user-images.githubusercontent.com/18414281/185197641-9c64b3bf-c583-466c-85ce-66c4ddd90717.png">

**Comment by ShruthiHubb** [comment]
Hi @KeJunMao can you give us more context here to troubleshoot this issue?

Thanks
Shruthi Kini

**Comment by KeJunMao** [comment]
Hi @ShruthiHubb 

check here
https://github.com/harness/drone/pull/3250#issuecomment-1232327333

or use curl
```bash
curl -X GET --header 'Content-Type: application/json;charset=UTF-8' 'https://gitee.com/api/v5/users/Ke_Jun/repos?type=all&sort=full_name&page=1&per_page=20'
```
check response `root[3]`


```json
...
"id": 1039816
"full_name": "Ke_Jun/Storyline-2-User-Guide-zh_cn"
"human_name": "Ke_Jun/Storyline 2 User Guide-zh_cn"
"url": "https://gitee.com/api/v5/repos/Ke_Jun/Storyline-2-User-Guide-zh_cn"
"namespace": 5 properties
"path": "Storyline-2-User-Guide-zh_cn"
"name": "Storyline 2 User Guide-zh_cn"
"owner": 17 properties
"assigner": 17 properties
"description": "storyline2用户指南-简体中文"
...
```

the `human_name` include space, but [drone](https://github.com/harness/drone) should use `full_name` as `slug`

**Comment by bradrydzewski** [comment]
I cannot comment on Gitee since I do not have any experience, but Bitbucket has similar options, and for Bitbucket we use the `full_name` equivalent.  I suspect we should use `full_name` for Gitee too. Since Gitee is a community contribution and is community supported (and is not formally supported by the Drone team) we would kindly ask for a pull request from the community to resolve this issue.  Thanks!

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/go-scm/pull/226
