### ISSUE TITLE
gitlab: force_remove_source_branch type is inconsistent

### ISSUE THREAD

**Issue by zzhzero** [drone/go-scm#228]
[https://gitlab.com/gitlab-org/gitlab/-/issues/15647](https://gitlab.com/gitlab-org/gitlab/-/issues/15647)
[https://gitlab.com/gitlab-org/gitlab/-/issues/15647#note_1133220749](https://gitlab.com/gitlab-org/gitlab/-/issues/15647#note_1133220749)

**Comment by bradrydzewski** [comment]
can you please provide more details?  I read the title and looked at the issues, but it is unclear what problems you are facing with the library and what actions need to be taken.

**Comment by zzhzero** [comment]
sorry i just realized i was using a historical version of this project
