### ISSUE TITLE
Gogs commit fails to deserialize commitDetails in some cases

### ISSUE THREAD

**Issue by GerkinDev** [drone/go-scm#231]
Hi,

Using the Drone CI Web UI, I can't create a build for a repository hosted on Gogs. The error was kinda unhelpful (no stack trace, not even in logs) and was something like this responded in the HTTP response:

```json
{"message":"json: cannot unmarshal number into Go value of type gogs.commitDetail"}
```

I cloned the source code & tried to dig a bit around what was happening. By using the current `master` branch of drone/go-scm as a replacement of `github.com/drone/go-scm v1.24.0`, the issue magically disappeared.

https://github.com/harness/drone/blob/99cb5c1456511aa137b7fff394b0dadde109db55/go.mod#L23

I tried to roll back in time and it appeared that my particular issue was fixed by https://github.com/drone/go-scm/pull/209; unfortunatelly, it is not released.

Would it be possible to have a release of the scm package, and drone server too using the new release ?

**Comment by jimsheldon** [comment]
Hello @GerkinDev thanks for investigating and opening this.

It sounds like your problem would be fixed if go-scm is updated to the latest version (1.27.0) in the drone server?

Would you be open to submitting a PR to the drone repo with that change, then we can close this issue? Thanks

**Comment by jimsheldon** [comment]
I missed that the change you are looking for is not part of a release yet, we will work on cutting a new release.

**Comment by GerkinDev** [comment]
Hi, yeah it's not released; that's why I opened the issue here.

I see you're super reactive: https://github.com/drone/go-scm/pull/232 thank you !

**Comment by jimsheldon** [comment]
No problem! I'll close this out.
