### ISSUE TITLE
Bitbucket Build Status Empty

### ISSUE THREAD

**Issue by blopker** [drone/go-scm#27]
Hello, I found a small issue with the way the Bitbucket build statuses are being posted. The issue, I think, is that the "name" field isn't being supplied to the Bitbucket API. The effect is that  although the build is green in the PR UI, there's no link to Drone. This only affects the new (beta) PR UI, which can be enabled in a user's settings (Bitbucket Labs).

Expected behavior is that a link shows up next to the build status in the new PR UI. Example from a Jenkins build:
![image](https://user-images.githubusercontent.com/757503/59085975-3586de00-88b5-11e9-92c0-78c4f196abb1.png)

The observed behavior is that the build status is shown, but there's no link:
![image](https://user-images.githubusercontent.com/757503/59086019-52231600-88b5-11e9-9de8-9318d80ec705.png)

The string I see from our Jenkins builds is from the optional "name" field, so I think that's all that needs to be added. As far as I can tell, this is in the `CreateStatus` function in https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/repo.go. Adding `Name:   input.Label` to the `status` struct should do the trick, although it might be nicer to have "name" set to the label plus the build number.

Cheers!

**Comment by bradrydzewski** [comment]
@blopker I was wondering if you could create a working example with CURL for creating a status that I could reference?  We have both `name` and `key` in the payload for compatibility with old and new versions and I'm seeing the status appear.

```
type status struct {
	State string `json:"state"`
	Key   string `json:"key"`
	Name  string `json:"name"`
	URL   string `json:"url"`
	Desc  string `json:"description"`
}
```

Unfortunately, I do not have the option to Bitbucket Labs for my installation (trying to figure that out too). But in the meantime, if there is a CURL I can use to replicate I should be able to fix. Thanks!

**Comment by blopker** [comment]
You mentioned Bitbucket Server, but this is for Bitbucket Cloud, sorry for the confusion. 

To get to the Labs page, you go to bitbucket.org and click on your profile:
![image](https://user-images.githubusercontent.com/757503/65448157-04430700-dded-11e9-9850-98d416999c06.png)
Then click on Bitbucket Labs.

The feature is called "New pull request experience":
![image](https://user-images.githubusercontent.com/757503/65450024-19219980-ddf1-11e9-86a0-a154fe357bda.png)

However, it now appears that Bitbucket is displaying something which fixes the usability issue of not being able to click on the status and get to the build in Drone.

The status now looks like: 
![image](https://user-images.githubusercontent.com/757503/65450153-56862700-ddf1-11e9-9fc0-b7ad829a0662.png)

Since the link is now clickable I think the main issue here is gone. Still it might be nice to have a custom status link containing the build number, like Jenkins does.

**Comment by bradrydzewski** [comment]
> You mentioned Bitbucket Server, but this is for Bitbucket Cloud, sorry for the confusion.

ah, thanks, I was making the wrong assumptions.  Thank you for clarifying, as this should now be much easier to track down :)

**Comment by bradrydzewski** [comment]
I fixed this at the library level so that we can supply a more user-friendly title. Do you have a preference of how you would like to format the title?  I am leaning toward `Build #42` but am open to suggestions.

![Uploading Screen Shot 2019-09-25 at 11.57.33 AM.png…]()

**Comment by tboerger** [comment]
What about drone/24? Build is already written below it so it's redundant.

**Comment by blopker** [comment]
I'm trying to think of what other info would be useful there. Maybe the branch name? Something like: `#24 my_great_feature`.

**Comment by bradrydzewski** [comment]
we will make this customizable in the server. In the meantime, we have this resolved in master and in `:latest` and I'm planning to cut a tag this weekend. So we should be all set.
