### ISSUE TITLE
Stash driver doesn't work for domain (@) users

### ISSUE THREAD

**Issue by fitz123** [drone/go-scm#31]
Stash server is expecting **slug** for `rest/api/1.0/users/` request instead of _login_ (which is used now by the driver)
https://docs.atlassian.com/DAC/rest/stash/3.11.3/stash-rest.html#idp331680

So any user which has `@` (as part of a username), for example `john_doe@acme.com` got User Not Found during OAuth process 

#25

**Comment by bradrydzewski** [comment]
ok, I have been thinking through this and here is my proposal.

1. use the existing API call to get the user ID
2. if that returns an error, try using the approach in https://github.com/drone/go-scm/pull/26

note that we should adjust the approach in https://github.com/drone/go-scm/pull/26 to ensure the username is an exact match. The filter will return the _closest_ match and could therefore return the wrong id. We have to do something similar for branches. See [this code](https://github.com/drone/go-scm/blob/fff0b070bb93b4cd0c738d7d9c94ed835d04c96f/scm/driver/stash/git.go#L31) for reference.

**Comment by bradrydzewski** [comment]
fixed by 0d1ea63283ade84c062be2b6ce5971ec9e1245cd

will be included in Drone 1.5.0 release
