### ISSUE TITLE
Support for listing the contents of a directory

### ISSUE THREAD

**Issue by Oduig** [drone/go-scm#36]
**Feature request**
I would like to call `Client.Contents.Find` to discover which files and directories exist within a directory.

**Use case**
This is an issue for the implementation of drone config plugins that require traversing the source repository, such as `drone-tree-config`. See https://github.com/bitsbeats/drone-tree-config/issues/2

**Details**
The GitHub API call to `repos/%s/contents/path` accepts directories, but the source code of `go-scm` [assumes that you're calling it on a file](https://github.com/drone/go-scm/blob/master/scm/driver/github/content.go), causing it to crash because the response has a different format than the one expected. See https://developer.github.com/v3/repos/contents/#get-contents.

Is this a feature that you could see making it into `go-scm`, or should Drone plugins preferably implement their own git integration logic?

**Comment by tboerger** [comment]
At least for me it makes sense to have this features as part of the lib to get these features easily into the drone extensions.

**Comment by bradrydzewski** [comment]
I am open to adding additional functions, but they need to be implemented for _all_ providers when possible. I recognize this is a significant amount of work, but it is the only way to ensure we have the correct abstractions in place. This means a pull request that implements the feature for a single provider (e.g. github only) would not be accepted.

**Comment by chhsia0** [comment]
I'm also having a need for this now so working on an implementation :) Will post a PR today.
