### ISSUE TITLE
State not set for Gitea commit status

### ISSUE THREAD

**Issue by xiian** [drone/go-scm#5]
I haven't been able to get Drone's status to be reflected back in Gitea. When I look at the commit status via the Gitea API, I see that statuses have been created from drone with almost all the right information, but the `status` field is an empty string.

The webhook to gitea's status API seems to be based on [Github's Status API](https://developer.github.com/v3/repos/statuses/#create-a-status), which has `state` instead of `status` for the JSON object being posted.

Manually editing the HTTP request Drone makes back to gitea to change the object key from `status` to `state` seems to do what is wanted.

Looks like [this line](https://github.com/drone/go-scm/commit/4893adc2e3aa4af7fb21aa26a6d44e9ac103c119#diff-fd7604443e1ca3e50f42f185bb6da237R155) should have `json:"state"` instead.

Making this an issue instead of a PR because I'm not entirely sure if I've got it all right in my head and have only done a little bit of research on this so far.

**Comment by bradrydzewski** [comment]
fixed with https://github.com/drone/go-scm/commit/23447efca3b7587b0a40747a99185b384066d4dc

**Comment by xiian** [comment]
Thanks for fixing this! 👍
