### ISSUE TITLE
support for create and update content?

### ISSUE THREAD

**Issue by soulseen** [drone/go-scm#55]
There are lots of  projects need to operate content, what about the idea of support creates and updates content?
if need, I can provide some help.
https://github.com/drone/go-scm/blob/master/scm/driver/github/content.go#L31

**Comment by tboerger** [comment]
It's great to add more functionality, but it should be available for all the supported providers, otherwise the library wouldn't make sense at all.

**Comment by soulseen** [comment]
yes, this pr https://github.com/drone/go-scm/pull/54 supported github, we can supported all providers step by step.

**Comment by bradrydzewski** [comment]
closed by #54
