### ISSUE TITLE
what is idea about creating the Request with header of `"Content-Type": "application/x-www-form-urlencoded"`?

### ISSUE THREAD

**Issue by soulseen** [drone/go-scm#56]
why must use header of `"Content-Type": "application/json"` in [here](https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/bitbucket.go#L71), 
if I want to create the Request with header of `"Content-Type": "application/x-www-form-urlencoded"`, like [this](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/src#post) , what should I do?

**Comment by bradrydzewski** [comment]
the purpose of this plugin is to abstract away provider-specific implementation details.  If you care deeply about using provider-specific implementation details such as hook content types you may consider using [go-github](https://github.com/google/go-github) which is going to expose more github functionality than this library.
