### ISSUE TITLE
Update GitLab Status API Endpoint

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-scm#6]
It looks like we are using a deprecated endpoint here:
https://github.com/drone/go-scm/blob/master/scm/driver/gitlab/repo.go#L149

need to change to this:
https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit

**Comment by tboerger** [comment]
Maybe you just configured something wrong? The current Gitlab api have been deprecated, but not dropped.

**Comment by t794104** [comment]
Confirmed the error : 
Drone 1.0.0.rc5
Gitlab 11.2.3

Jobs doe not update status in gitlab; in my apach logging (usesd as proxy) i have the following lines 👍 
"POST /api/v4/projects/cicd%2Fyamllint/repository/commits/2c8c789a06f81959cf992ddc66c73d8632ab06d4/statuses?name=continuous-integration%2Fdrone%2Fpush&state=pending&target_url=http%3A%2F%2Fdrone.mgmt3.cisnet%2Fcicd%2Fyamllint%2F1 HTTP/1.1" **404** 25

It looks like a simple url update too get it working ;
path := fmt.Sprintf("api/v4/projects/%s/statuses/%s?%s", encode(repo), ref, params.Encode())
  
how do i do this and test it ? can you @bradrydzewski build me a tc6 i can test ?

**Comment by tboerger** [comment]
You could use the integration test suite part of this repo to test your change

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/go-scm/commit/57adc7045a172d3e01b4a25805a60ed5f6033054
