### ISSUE TITLE
paginate Gitea repository list

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-scm#64]
Gitea implemented pagination for the repository list which results in only 10 repositories being returned. We have mechanisms in place for handling pagination. Here is a note from our Discourse forum:

> Pagination would need to be added to the code here:
https://github.com/drone/go-scm/blob/master/scm/driver/gitea/repo.go#L42
> 
> For reference you can see how we do this with GitHub:
https://github.com/drone/go-scm/blob/master/scm/river/github/repo.go#L85
> 
> Some additional code may be required to extract the pagination data from the response (i.e. current page, next page, last page, results per page). However, if Gitea uses the same approach as GitHub (example below) than this would not require any additional code.
> 
>```text
>Link: <https://api.github.com/user/repos?page=3&per_page=100>; rel="next",
>  <https://api.github.com/user/repos?page=50&per_page=100>; rel="last"
>```

_Source: https://discourse.drone.io/t/drone-only-shows-10-repositories-from-gitea/6922/16_

**Comment by ryanjaeb** [comment]
There's a [Gitea PR](https://github.com/go-gitea/gitea/pull/11827) that says it fixed this to work without any Drone changes.  I don't have 10+ repos to test it easily, but, for anyone that was having a problem, the `linux-amd64` Docker image looks like it already [includes](https://hub.docker.com/layers/gitea/gitea/linux-amd64/images/sha256-053af026266112fd18d6ab4d3bb89c3fbb56f7276a63a1d16342c50d9637876b?context=explore) the changes  (`org.label-schema.vcs-ref=48842ed1`).

**Comment by xf-** [comment]
@bradrydzewski paging in frontend has a limit parameter - couldn't you increase it to 1000?

e.g.
`https://gitserver/api/v1/repos/search?sort=updated&order=desc&uid=1&q=&page=1&limit=1000&mode=&archived=false`

**Comment by moepman** [comment]
I think it is still broken with Gitea 1.12.0 - see https://github.com/go-gitea/gitea/issues/11970

**Comment by lafriks** [comment]
Just tested on try.gitea.io and it does seem to return correct header:
```
content-length: 2484
content-type: application/json; charset=UTF-8
date: Fri19 Jun 2020 10:25:04 GMT
link: <https://try.gitea.io/api/v1/user/repos?access_token=xxx&limit=2&page=2>; rel="next",<https://try.gitea.io/api/v1/user/repos?access_token=xxx&limit=2&page=5>; rel="last"
x-content-type-options: nosniff
x-firefox-spdy: h2
x-frame-options: SAMEORIGIN
x-total-count: 9 
```

**Comment by lafriks** [comment]
@bradrydzewski If there anything needs to be fixed on gitea side please let me know

**Comment by moepman** [comment]
@lafriks
> Just tested on try.gitea.io and it does seem to return needed header:
> 
> ```
> content-length: 2484
> content-type: application/json; charset=UTF-8
> date: Fri19 Jun 2020 10:25:04 GMT
> link: <https://try.gitea.io/api/v1/user/repos?access_token=xxx&limit=2&page=2>; rel="next",<https://try.gitea.io/api/v1/user/repos?access_token=xxx&limit=2&page=5>; rel="last"
> x-content-type-options: nosniff
> x-firefox-spdy: h2
> x-frame-options: SAMEORIGIN
> x-total-count: 9 
> ```

I think the effect will only be there if you have more than 30 repositories, see my gitea issue for more Details.
