### ISSUE TITLE
Adding code for files changed in the commit range?

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-scm#80]
This was brought up in https://github.com/meltwater/drone-convert-pathschanged/issues/34

Would it make sense to add functions to this project similar to https://github.com/meltwater/drone-convert-pathschanged/blob/master/providers/github.go#L13 which can determine the files changes in a commit range?

If so, we can work on a pull request.

**Comment by bradrydzewski** [comment]
I think we may have all functions needed.  We have both `FindCommit` and a `CompareChanges` function:
https://github.com/drone/go-scm/blob/master/scm/driver/github/git.go#L26
https://github.com/drone/go-scm/blob/master/scm/driver/github/git.go#L68

**Comment by jimsheldon** [comment]
Thanks, I will put something in our backlog around this, we'll get a pull request together soon.
