### ISSUE TITLE
Failure when PR labels are queried on Bitbucket Cloud

### ISSUE THREAD

**Issue by Naensma** [drone/go-scm#86]
On my Jenkins-X installation using Bitbucket Cloud git provider whenever 
lighthouse-webhook handles a PullRequestEvent it fails:

"could not get labels for PR /:83 in WIP plugin: Not Supported"

**Comment by bradrydzewski** [comment]
can you please provide more information?  I do not use JenkinsX and do not understand what needs to be fixed in this library.

**Comment by Naensma** [comment]
You are right, its an issue with jenkinsx fork. Sorry!
