### ISSUE TITLE
Drone and Bitbucket broken for write permission detection for drone build restart permission.

### ISSUE THREAD

**Issue by RichardTheHouse** [drone/go-scm#87]
Since this commit:
https://github.com/drone/go-scm/commit/802e265b418f445ceec60827537bb5c7071cb018

Changing of 
	path := fmt.Sprintf("rest/api/1.0/repos?size=1000&permission=REPO_WRITE&project=%s&name=%s", namespace, name)
to 
	path := fmt.Sprintf("rest/api/1.0/repos?size=1000&permission=REPO_WRITE&projectname=%s&name=%s", namespace, name)

Has resulted in drone not allowing users with write permission to restart drone jobs or do drone deploys. As it is not detecting the user has write permission.

Admins still work using the webhook lookup but users with only write permission can not.

**Comment by bradrydzewski** [comment]
I will take a look.  The reason we changed was because, according to bitbucket rest documentation, there is no `project` parameter (https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8296923984).  The `projectname` parameter should prevent the situation where two repositories exist with the same name, but under different project, that we don't choose the wrong repository.

**Comment by bradrydzewski** [comment]
I spent some time attempting to reproduce but was unable.  I tried to be very detailed with my testing and methodology below.  Perhaps you can take a look and provide some feedback?

---

First, I setup a project called `foo` and repository called `quux` and then created and granted a dummy user account access to this project. Here is a screenshot that demonstrates access granted to this repository:

<img width="1312" alt="Screen Shot 2020-12-15 at 2 14 39 PM" src="https://user-images.githubusercontent.com/817538/102261675-fee54700-3edf-11eb-99b5-a2fec8be6cb6.png">


Next, I made the an API call on behalf of the dummy user account using the curl command:

```
curl -H "Authorization: Bearer XXXXXX" 'http://XXX.XXX.XXX.XXX:7990/rest/api/1.0/repos?permission=REPO_WRITE&limit=1&projectname=foo'
```

And received the results as expected indicating write access:
```json
{
    "size": 1,
    "limit": 1,
    "isLastPage": true,
    "values": [
        {
            "slug": "quux",
            "id": 5,
            "name": "quux",
            "scmId": "git",
            "state": "AVAILABLE",
            "statusMessage": "Available",
            "forkable": true,
            "project": {
                "key": "FOO",
                "id": 3,
                "name": "foo",
                "public": false,
                "type": "NORMAL",
                "links": {
                    "self": [
                        {
                            "href": "http://165.227.13.235:7990/projects/FOO"
                        }
                    ]
                }
            },
            "public": false,
            "links": {
                "clone": [
                    {
                        "href": "http://jcitizen@165.227.13.235:7990/scm/foo/quux.git",
                        "name": "http"
                    },
                    {
                        "href": "ssh://git@165.227.13.235:7999/foo/quux.git",
                        "name": "ssh"
                    }
                ],
                "self": [
                    {
                        "href": "http://165.227.13.235:7990/projects/FOO/repos/quux/browse"
                    }
                ]
            }
        }
    ],
    "start": 0
}
```

Next, I decided to login to Drone as the dummy user and sync my account.  I can see the repository in my list:

<img width="854" alt="Screen Shot 2020-12-15 at 3 00 35 PM" src="https://user-images.githubusercontent.com/817538/102266841-00663d80-3ee7-11eb-9d79-cac85e14de2a.png">


Next I clicked on the repository.  When you perform a repository sync, Drone purges its cache of repository access levels for the user, forcing Drone to fetch and update the access levels for each repository.  The results are cached in the database until the next time you re-sync your repository list.  As part of our testing, we can confirm in the logs that Drone makes an API call to Bitbucket (using this library) which returns that the dummy user is granted write access to the repository:

<img width="489" alt="Screen Shot 2020-12-15 at 3 01 27 PM" src="https://user-images.githubusercontent.com/817538/102267162-7a96c200-3ee7-11eb-982a-659fc9bd93ad.png">


Finally, I checked to make sure write access was persisted in the database and returned from the API when the user attempts to request the repository resource:

<img width="861" alt="Screen Shot 2020-12-15 at 3 01 58 PM" src="https://user-images.githubusercontent.com/817538/102267429-e11be000-3ee7-11eb-98be-bedf6e48f325.png">

**Comment by RichardTheHouse** [comment]
Thank you for looking, I think I can see the issue and why it works for you and not us:
The project key and project name are getting mixed up, in your example you have called them both "FOO"

Try changing your project name to be different from the key in bitbucket:

{
    "size": 1,
    "limit": 1,
    "isLastPage": true,
    "values": [
        {
            "slug": "quux",
            "id": 5,
            "name": "quux",
            "scmId": "git",
            "state": "AVAILABLE",
            "statusMessage": "Available",
            "forkable": true,
            "project": {
                "key": "FOO",
                "id": 3,
                **"name": "Some other Name not starting with FOO",**
                "public": false,
                "type": "NORMAL"
            },
            "public": false
        }
    ],
    "start": 0
}

![image](https://user-images.githubusercontent.com/10982524/105380712-211c6400-5c06-11eb-8ea3-f7cbf599a4f7.png)

**Comment by RichardTheHouse** [comment]
Anyone else who comes across this bug can work around it by renaming the project to start with the key:
Project Name:  FOO - Some project description
Project key:      FOO

**Comment by pedroparraortega** [comment]
Hi, i think i'm hitting a similar issue in our deployment. We are running drone server 1.10.1 together with bitbucket server and even if the user has write permissions in bitbucket drone seems to not be able to recognise it.

![Screen Shot 2021-05-19 at 08 57 19](https://user-images.githubusercontent.com/7081272/118785515-35f5c500-b891-11eb-87ba-5c55a9a92f34.png)
![Screen Shot 2021-05-19 at 10 55 11](https://user-images.githubusercontent.com/7081272/118785530-3a21e280-b891-11eb-8b3d-a587f66c910b.png)
![Screen Shot 2021-05-19 at 09 58 33](https://user-images.githubusercontent.com/7081272/118785538-3d1cd300-b891-11eb-816e-c0536b497d34.png)

**Comment by pedroparraortega** [comment]
> Hi, i think i'm hitting a similar issue in our deployment. We are running drone server 1.10.1 together with bitbucket server and even if the user has write permissions in bitbucket drone seems to not be able to recognise it.
> 
> ![Screen Shot 2021-05-19 at 08 57 19](https://user-images.githubusercontent.com/7081272/118785515-35f5c500-b891-11eb-87ba-5c55a9a92f34.png)
> ![Screen Shot 2021-05-19 at 10 55 11](https://user-images.githubusercontent.com/7081272/118785530-3a21e280-b891-11eb-8b3d-a587f66c910b.png)
> ![Screen Shot 2021-05-19 at 09 58 33](https://user-images.githubusercontent.com/7081272/118785538-3d1cd300-b891-11eb-816e-c0536b497d34.png)

i've rolled back the drone server from 1.10.1 to 1.9.1 and it is working 
```{"id":632,"uid":"791","user_id":63,"namespace":"OPSA","name":"administration-service","slug":"OPSA/administration-service","scm":"","git_http_url":"https://bitbucket.voiceworks.com/scm/opsa/administration-service.git","git_ssh_url":"ssh://git@bitbucket.voiceworks.com/opsa/administration-service.git","link":"https://bitbucket.voiceworks.com/projects/OPSA/repos/administration-service/browse","default_branch":"master","private":true,"visibility":"private","active":true,"config_path":".drone.yml","trusted":false,"protected":false,"ignore_forks":false,"ignore_pull_requests":false,"auto_cancel_pull_requests":false,"auto_cancel_pushes":false,"timeout":60,"counter":159,"synced":1602888751,"created":1602888751,"updated":1602888751,"version":161,"permissions":{"read":true,"write":true,"admin":false}}````

With 1.9.1 i get the proper permissions.

**Comment by pedroparraortega** [comment]
just verified that something changed from 1.7.1 to 1.7.2 that changed the behavior

**Comment by tphoney** [comment]
With #114 we have submitted a fix and are doing a release of the library, can you check it out.

**Comment by tphoney** [comment]
thanks for your patience @RichardTheHouse
