### ISSUE TITLE
the event pr:from_ref_updated is unknown with Bitbucket Server v6.10.5

### ISSUE THREAD

**Issue by bakito** [drone/go-scm#88]
I'm running drone 1.10.1 (depending on drone/go-scm v1.8.0) with Bitbucket Server v6.10.5

With this combination the activation of repositories fails with the following error message:

`{"message":"the event pr:from_ref_updated is unknown"}`

 This was working with drone 1.9.1

**Comment by ashwilliams1** [comment]
drone 1.10.1 added support for the bitbucket `pr:from_ref_updated` event which is only available in bitbucket 7.x and higher, which causes problems with older version of bitbucket.

**Comment by bakito** [comment]
Is there a possibility to have backaward compability by making the fields optional?

**Comment by bakito** [comment]
https://discourse.drone.io/t/attempt-to-enable-repo-on-older-bitbucket-servers-fails/8486
